on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

        with:
          node-version: '18.x'

      - name: GA薅羊毛专项——企业微信webhook
        uses: walkthunder/action-wecom-webhook@v1.1.2
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: template_card
          template_card: '{
            "msgtype":"template_card",
            "template_card":{
                "card_type":"text_notice",
                "source":{
                    "desc": "${{ github.repository }}",
                    "desc_color":0
                },
                "main_title":{
                    "title":"CI 通知",
                    "desc":"Github action 执行完毕"
                },
                "emphasis_content":{
                    "title": "${{ job.status }}",
                    "desc": "${{ github.workflow }} / ${{ github.repository }}"
                },
                "sub_title_text":"workflow details",
                "horizontal_content_list":[
                    {
                        "keyname": "build",
                        "value": "${{ job.status }}"
                    }
                ],
                "jump_list":[
                    {
                        "type":1,
                        "url": "${{ github.repository }}",
                        "title":"Github Repo Link"
                    }
                ],
                "card_action":{
                    "type":1,
                    "url": "${{ github.repository }}"
                }
            }
        }'