name: PackageHook

on: repository_dispatch


jobs:
  run_if_failure:
    # if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: action - ${{github.event.action}} | branch - ${{github.event.branch}} | insta - ${{github.event.installation}} | repo - ${{github.event.repository}} | sender - ${{github.event.sender}} | type -  ${{github.event.event_type}} | client_payload - ${{ github.event.client_payload }}
        run: echo $MESSAGE
