name: PackageHook

on: repository_dispatch


jobs:
  run_if_failure:
    # if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: action - ${{github.event.action}} client_payload - ${{ github.event.client_payload.mac }} - ${{ github.event.client_payload.mas }}
        run: echo $MESSAGE
